[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.17"
solana-sdk = "1.17"
solana-program = "1.17"
borsh = "0.10"
tokio = { version = "1.28", features = ["full"] }
anchor-lang = "0.30.1"  
anchor-client = "0.30.1"